package viz.runtime;

public enum Change {
	NONE, NEW, REMOVED,
	VALUE_CHANGED, DIFF_OBJECT_SAME_TYPE,
	DIFF_OBJECT_SAME_TYPE_DIFF_FIELD_SIZE,
	DIFF_OBJECT_DIFF_TYPE,
	TO_NULL, NULL_TO_OBJ,
	CIRCULAR
}
